### PR TITLE
Replace falsey checks with undefined checks

### LINKED ISSUE #3: Fix TypeError when map has either 0 sliders or 0 hit circles
Error message:

```
TypeError: nsliders, ncircles, nobjects are required
    at std_ppv2.calc (./node_modules/ojsama/ojsama.js:1619:19)
    at Object.ppv2 (./node_modules/ojsama/ojsama.js:1838:31)
```

### PR DESCRIPTION
**Pull request by oamaok**
Should fix #3

### CODE REVIEW

**Comment by Francesco149** [comment]
thanks!

**Comment by Francesco149** [comment]
the falsey checks always get me in js since I don't write it that often (^:

**Review by LeaPhant — COMMENTED** [review]
Wouldn't using `isNaN` be more fitting so it also returns a TypeError for invalid inputs like strings?

**Comment by oamaok** [comment]
Good point.

**Comment by Francesco149** [comment]
yes, I will consider changing to isNaN, but this PR is perfectly fine as it went more closely with what the code was originally doing.

btw this is now live on the npm package :ok_hand:

**Comment by oamaok** [comment]
Also, I fucked up: the undefined check doesn't even work, since it's not comparing it to the string `"undefined"`, but to the actual `undefined`. This PR actually broke all the checks :D

**Comment by Francesco149** [comment]
lolol I thought it was some alternative way to do it but I guess not

**Comment by Francesco149** [comment]
anyways I'm changing some of them to isNaN (the required params ones) and leaving others with isUndefined so that it doesn't silently replace wrong types with default values

**Pull request merged**
