### PR TITLE
2018-2019 pp changes

### PR DESCRIPTION
**Pull request by Francesco149**
don't merge until we have official data to regen the test suite

### CODE REVIEW

**Comment by Francesco149** [comment]
gonna be using this to merge the other pp changes, WIP...

**Comment by oamaok** [comment]
is this already a working version? could use this for ezpp before the merge, even. thank you for keeping up with the updates!

**Comment by ghost** [comment]
@oamaok This is definitely not a very polished version as of right now. It works flawlessly, however the results constantly deviate from the "should" values by roughly 1.5-2pp, no more / less though. If that's within your margin of error you can use it right now. The changes are non breaking, you can simply drop it in, however for others this may be too inaccurate in this state right now. @Francesco149 any follow up on this? 😃

**Comment by oamaok** [comment]
@Iyo well better to have quick approximations quick rather than keeping the old values for now. it's not like ezpp! has the reputation for being the most accurate thing in the first place :D

**Comment by Francesco149** [comment]
yes this is an approximation, as it has always been, expect inaccuracies due to missing slider calculations

and yea this is ready for use, but I'd like to test it against a large set of scores before merging so I'm waiting for the site to fully update scores so I can regenerate the test suite

for the time being you can just switch to this branch if you want to use it early

**Comment by oamaok** [comment]
yeah I updated the ext with the branch, just gonna do an update once this is done. thanks again for your work.

**Pull request merged**
